-- This is the final, corrected master script using a more robust INSERT...SELECT syntax.
BEGIN;

-- First, completely wipe the existing links table to ensure a clean slate.
TRUNCATE TABLE public.references_biblio RESTART IDENTITY;

-- Now, insert the correct link for each bibliography using a safe CROSS JOIN method.
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '55' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Additions au plan de la ville d''Alexandrie”, Bulletin de la Société Archéologique d''Alexandrie 1' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '125' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Additions au plan d''Alexandrie”, Bulletin de la Société Archéologique d''Alexandrie 2' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '116' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Alexandria University Excavations on the Cricket Playgrounds in Alexandria”, Opuscula Romana IX' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '104' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Alexandrie 1992-1993”, Bulletin de Correspondance Hellénique 118' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '40' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Alexandrie 1994”, Bulletin de Correspondance Hellénique 119' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '129' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Alexandrie 1994”, Bulletin de Correspondance Hellénique 120' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '17' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Alexandrie 1996”, Bulletin de Correspondance Hellénique 121' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '7' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Alexandrie 1997”, Bulletin de Correspondance Hellénique 122' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '84' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Alexandrie 2000”, Bulletin de Correspondance Hellénique 125' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '106' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Alexandrie 2001”, Bulletin de Correspondance Hellénique 126' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '20' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Antiquités découvertes à Maamourah”, Bulletin de la Société Archéologique d''Alexandrie 8' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '60' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Citerne el-Nabih un dispositif remarquable de l’hydraulique alexandrine”, Du Nil à Alexandrie : Histoires d’eaux' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '74' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Cronaca del museo e degli scavi e ritrovamenti nel territorio di Alessandria”, Bulletin de la Société Archéologique d''Alexandrie 10' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '71' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Cronaca del museo e degli scavi e ritrovamenti nel territorio di Alessandria”, Bulletin de la Société Archéologique d''Alexandrie 7' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '76' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Cronaca del museo e degli scavi e ritrovamenti nel territorio di Alessandria”, Bulletin de la Société Archéologique d''Alexandrie 9' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '47' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Descriptions des antiquités d''Alexandrie et de ses environs”, Description de l''Égypte, Antiquités V' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '122' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Documents et nouvelles”, Bulletin de la Société Archéologique d''Alexandrie 18' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '44' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Excavations on the Gouvernment Hospital site”, Preliminary Report' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '59' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Fouilles et travaux en Egypte et au Soudan 1992-1993 : Alexandrie”, Orientalia 63' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '87' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Investigation of a trench near the Via Canopica in Alexandria”, Bulletin de la Société Archéologique d''Alexandrie 44' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '35' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“L''ancienne Alexandrie”, Étude archéologique et topographique' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '87' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“La côte Alexandrine dans l''Antiquité”, Bulletin de la Société Khédiviale de Géographie' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '111' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Le temple de Césaerum et l''Église patriarcale”, Bulletin de la Société Khédiviale de Géographie' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '117' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Les citernes d''Alexandrie”, Bulletin de la Société Archéologique d''Alexandrie 2' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '117' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Les citernes et les chapiteaux”, Alexandriaca I, Bd''Et._XCVII/1_Mélanges Gamal Eddin Mokhtar' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '51' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Les habitations romaines tardives d''Alexandrie à la lumière des fouilles polonaises à Kom el Dikka”, Alexandrie III' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '97' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Neue Untersuchungen in Alexandrien”, AM 25' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '64' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Notes épigraphiques”, Bulletin de la Société Archéologique d''Alexandrie 2' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '72' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Recent discoveries in the Royal Quarter of Alexandria”, Bulletin de la Société Archéologique d''Alexandrie 44' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '4' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Report on prospects of research in Alexandria”, Egypt Exploration Fund' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '61' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Saggio di una pianta archeologica di Alessandria”, Annuario 1932-1933' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '95' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Scavi e scoperte alessandrine (1949-1952)”, Bulletin de la Société Archéologique d''Alexandrie 41' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '102' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Travaux de l''IFAO en 1997-1998 : Alexandrie”, Bulletin de l''Institut Français d''Archéologie Orientale' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '12' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Travaux de l''IFAO en 2000-2001 : Alexandrie”, Bulletin de l''Institut Français d''Archéologie Orientale' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '126' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Travaux de l''IFAO en 2001-2002 : Alexandrie”, Bulletin de l''Institut Français d''Archéologie Orientale' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '21' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Travaux de l''IFAO en 2002-2003 : Alexandrie”, Bulletin de l''Institut Français d''Archéologie Orientale' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '128' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Travaux de l''IFAO en 2003-2004 : Alexandrie”, Bulletin de l''Institut Français d''Archéologie Orientale' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '119' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = '“Vestiges d''un édifice ptolémaïque en bordure de la voie canopique, à Alexandrie”, Bulletin de la Société Archéologique d''Alexandrie 42' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '128' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Alexandrea ad Aegyptum' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '13' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Alexandrie et la Basse Égypte' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '16' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Annuaire du Musée Gréco-Romain 1935-1939' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '107' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Bulletin de la Société Archéologique d''Alexandrie 5' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '39' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Il Museo di Alessandria e gli scavi nell''anno 1892' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '54' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Le Musée Gréco-Romain 1925-1951' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '115' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Mémoire sur l''antique Alexandrie' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '108' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Modern Egypt and Thebes (I-II)' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '18' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Notice sur les fouilles récentes executées à Alexandrie 1874-1875' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '5' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Nouvelles découvertes dans le quartier de Basileia à Alexandrie, Et.Trav. 11' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '70' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Plan de la ville d''Alexandrie à l''époque ptolémaïque' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '23' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Rapport sur la bibliothèque municipale en 1898 et sur le musée gréco-romain, Le Musée gréco-romain d''Alexandrie (1892-1898)' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '80' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Rapport sur la marche du service du Musée pendant l''année 1906' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '103' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Rapport sur la marche du service du Musée pendant l''année 1922-1923' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '49' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Rapport sur la marche du service du Musée pendant l''exercice 1917-1918' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '19' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Rapport sur la marche du service du Musée pendant l''exercice 1921-1922' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '6' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Rapport sur les fouilles pratiquées et à pratiquer à Alexandrie' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '57' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Recherches sur les anciens monuments situés sur le Grand-Port d''Alexandrie' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '129' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Topografia e architettura, Repertorio d''Arte dell''Egitto Greco-Romano, série C' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '75' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Voyage d''Égypte et de Nubie' LIMIT 1) AS bib;
INSERT INTO public.references_biblio (id_decouverte, id_biblio) SELECT dec.id, bib.id FROM (SELECT d.id FROM decouvertes d JOIN sites_fouilles sf ON d.id_site = sf.id WHERE sf.fid = '126' LIMIT 1) AS dec, (SELECT id FROM bibliographies WHERE nom_document = 'Voyage d''Égypte et de Nubie' LIMIT 1) AS bib;

COMMIT;